CMS.Web/Controllers/FamilyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CMS.Data.Services;
using CMS.Data.Entities;

namespace CMS.Web.Controllers
{
    [Route("[controller]")]
    public class FamilyController : BaseController
    {
        private readonly IPatientService svc;

    public FamilyController()
    {
        svc = new PatientServiceDb();
    }

    // GET /family
    public IActionResult Index()
    {
        // load patients using service and pass to view
        var families = svc.GetAllMembers();
        
        return View(families);
    }

    // GET /family/details/{id}
    public IActionResult Details(int id)
    {
        var family = svc.GetMemberById(id);
      
        // check if family is null and alert/redirect 
        if (family is null) {
            Alert("Family Member Does not Exist", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }

        return View(family);
    }

    // GET: /family/create   
    public IActionResult Create()
    {
        // display blank form to create a family member
        var fm = new FamilyMember();
        //return the new family member to the view
        return View(fm);
    }

    // POST /family/create
    //[ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create(User fm)
    {   
      
        // complete POST action to add family member
        if (ModelState.IsValid)
        {
            // call service Addfamily method using data in svc
            var familymember = svc.AddMember(fm);
            if (familymember is null) 
            {
                Alert("Issue creating the family member", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Details), new { Id = familymember.Id});   
        }
        
        // redisplay the form for editing as there are validation errors
        return View(fm);
    }

    // GET /family/edit/{id}
    public IActionResult Edit(int id)
    {
        // load the family member using the service
        var family = svc.GetMemberById(id);

        // check if family is null and Alert/Redirect
        if (family is null)
        {
            Alert("Family member not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }  

        // pass patient to view for editing
        return View(family);
    }

    // POST /patient/edit/{id}
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Edit(int id, FamilyMember fm)
    {       
        // complete POST action to save family member changes
        if (ModelState.IsValid)
        {            
            var family = svc.GetMemberById(fm.Id);
            if (family is null) 
            {
                Alert("Issue editing the family member", AlertType.warning);
            }

            // redirect back to view the patient details
            return RedirectToAction(nameof(Details), new { Id = fm.Id });
        }

        // redisplay the form for editing as validation errors
        return View(fm);
    }

    // GET / family/delete/{id}   
    public IActionResult Delete(int id)
    {
        // load the family member using the service
        var family = svc.GetMemberById(id);
        // check the returned patient is not null and if so return NotFound()
        if (family == null)
        {
            Alert("Family Member not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }     
        
        // pass patient to view for deletion confirmation
        return View(family);
    }

    // POST /family/delete/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]   
    public IActionResult DeleteConfirm(int id)
    {
        // delete family member via service
        var deleted = svc.DeleteMember(id);
        if (deleted)
        {
            Alert("family member deleted", AlertType.success);            
        }
        else
        {
            Alert("family member could not  be deleted", AlertType.warning);           
        }
        
        // redirect to the index view
        return RedirectToAction(nameof(Index));
    }

}
}

CMS.Web/Views/Family/Create.cshtml
@* @model FamilyMember


<div class="card rounded shadow p-4">
    <h3>Create Family Member</h3>

    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <!-- name 2 columns in a row -->
        <div class="row mt-3">
            <div class="col">
                <label asp-for="Firstname" class="form-label"></label>
                <input asp-for="Firstname" class="form-control"/>
                <span  asp-validation-for="Firstname" class="text-danger"></span>
            </div>

            <div class="col">
                <label asp-for="Surname" class="form-label"></label>
                <input asp-for="Surname" class="form-control"/>
                <span  asp-validation-for="Surname" class="text-danger"></span>
            </div>
         </div>
        <!-- MobileNumber -->
         <div class="row mt-3">
        <div class="col">
            <label asp-for="MobileNumber" class="form-label"></label>
            <input asp-for="MobileNumber" class="form-control"/>
            <span  asp-validation-for="MobileNumber" class="text-danger"></span>
        </div>

        <!-- email -->
        <div class="col">
            <label asp-for="EmailAddress" class="form-label"></label>
            <input asp-for="EmailAddress" class="form-control"/>
            <span  asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
    </div>
                
        <div class="mt-3">
            <button type="submit" class="btn btn-primary" aria-label="create">Create</button>
            <a class="btn btn-secondary" asp-action="Index" aria-label="cancel">Cancel</a>
        </div>

    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

CMS.Web/Views/Family/Delete.cshtml
@* @model FamilyMember
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Family" asp-action="Index">Families</a></li>
        <li class="breadcrumb-item active" aria-current="page">Delete</li>
    </ol>
</nav>
<div class="card rounded shadow p-4">
  <h3 class="mb-4">Delete Family Member? <span class="ms-3 text-danger fs-5">Are you sure?</span></h3> 
  

  <!-- display the family using a <dl> as per Details.cshtml -->     
  <dl class="row">  
    <dt class="col-4 pb-1">Firstname</dt>
    <dd class="col-8 pb-1">@Model.Firstname</dd>

    <dt class="col-4 pb-1">Surname</dt>
    <dd class="col-8 pb-1">@Model.Surname</dd>

    <dt class="col-4 pb-1">MobileNumber</dt>
    <dd class="col-8 pb-1">@Model.MobileNumber</dd>

    <dt class="col-4 pb-1">EmailAddress</dt>
    <dd class="col-8 pb-1">@Model.EmailAddress</dd>

    <dt class="col-4 pb-1">PatientFamily</dt>
    <dd class="col-8 pb-1">@Model.PatientFamilies</dd>

  </dl>
  <div class="mt-4">
    <!-- form to submit post request to DeleteConfirm action     --> 
    <form asp-action="DeleteConfirm" asp-route-id="@Model.Id">
        <input type="hidden" asp-for="Id" class="form-control"/>
        <button type="submit" class="btn btn-danger" aria-label="delete">Delete</button>
        <a class="btn btn-secondary" asp-action="Details" asp-route-id="@Model.Id" >Cancel</a>
    </form>
  </div>
</div>

</div>
 *@

CMS.Web/Views/Family/Details.cshtml
@* @model FamilyMember
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Family" asp-action="Index">Patients</a></li>
        <li class="breadcrumb-item active" aria-current="page">Details</li>
    </ol>
</nav>
<h3 class="mt-4 mb-4">Family Member Details:          @Model.Firstname   @Model.Surname  </h3>        
<div class="card rounded shadow p-4">
    <!-- Display patient  details -->
    <div class="row">
        <!-- Details and Navigation -->
        <div class="col-8 d-flex flex-column justify-content-between">
            <!-- Patient details -->
            <div>
                <h2 class="mb-4 text-primary">Family Details</h2>
                <dl class="row">  

                    <dt class="col-4 pb-1">Firstname</dt>
                    <dd class="col-8 pb-1">@Model.Firstname</dd>
                    <dt class="col-4 pb-1">Surname</dt>
                    <dd class="col-8 pb-1">@Model.Surname</dd>
                    <dt class="col-4 pb-1">MobileNumber</dt>
                    <dd class="col-8 pb-1">@Model.MobileNumber</dd>
                    <dt class="col-4 pb-1">EmailAddress</dt>
                    <dd class="col-8 pb-1">@Model.EmailAddress</dd>
                    <dt class="col-4 pb-1">PatientFamily</dt>
                    <dd class="col-8 pb-1">@Model.PatientFamilies</dd>
                </dl>
            </div>
        </div>
    </div>    
</div>
<!-- action options -->
        <div class="mt-4 mb-4"> 
        <a asp-controller="Family" asp-action="Index" class="btn btn-primary"><i class="bi bi-list"></i>
            Patient List
        </a>    
        <a asp-controller="Family" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="bi bi-pen"></i>
            Edit Patient
        </a>  
        <a asp-controller="Family" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-primary"><i class = "bi bi-trash"></i>
            Delete
        </a> 
      </div>
 *@

CMS.Web/Views/Family/Edit.cshtml
@* @model Patient

<div class="card rounded shadow p-4">

    <h3>Edit Patient</h3>

    <form asp-action="Edit">
        
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <!-- hide the id as its not user editable but needs to be in the -->
        <!-- form to ensure the family passed to the controller is complete -->    
        <input type="hidden" asp-for="Id"/>
       
        <!-- name -->
        <div class="mt-3">
            <div class="row">
                <label asp-for="Firstname" class="form-label"></label>
                <input asp-for="Firstname" class="form-control"/>
                <span  asp-validation-for="Firstname" class="text-danger"></span>
            </div>

            <div class="row">
                <label asp-for="Surname" class="form-label"></label>
                <input asp-for="Surname" class="form-control"/>
                <span  asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
          <!-- mobile-number -->
        <div class="mt-3">
            <label asp-for="MobileNumber" class="form-label"></label>
            <input asp-for="MobileNumber" class="form-control"/>
            <span  asp-validation-for="MobileNumber" class="text-danger"></span>
        </div>


        <!-- email -->
        <div class="mt-3">
            <label asp-for="Email" class="form-label"></label>
            <input asp-for="Email" class="form-control"/>
            <span  asp-validation-for="Email" class="text-danger"></span>
        </div>


        <!-- submit button and cancel link which navigates to Index action -->
        <div class="mt-3">           
            <button type="submit" class="btn btn-primary" aria-label="save">Save</button>            
            <a class="btn btn-secondary" asp-action="Details" asp-route-id="@Model.Id" aria-label="cancel" >Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

CMS.Web/Views/Family/Index.cshtml
@* @model IList<FamilyMember>

<div class="card border rounded shadow p-4">

    <!-- Title bar -->
    <div class="d-flex align-items-center justify-content-between">
        <h3>Patient List</h3>
        
        <a class="btn btn-sm btn-primary" asp-action="create" title="add student" aria-label="add patient">
           <i class="bi bi-plus"></i> Create
        </a>
    </div>

    <!-- List of family members -->
    <table class="table table-hover mt-4">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Surname</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var p in Model)
            {
                <tr>
                    <td>@p.Id</td>
                    <td>@p.Firstname</td>
                    <td>@p.Surname</td>
                   
                    <td>                       
                        <a asp-action="Details" asp-route-id=@p.Id>
                            <i class="bi bi-display-fill me-2" title="view student" arial-label="view patient"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div> *@