CMS.Web/Controllers/CarerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CMS.Data.Services;
using CMS.Data.Entities;

namespace CMS.Web.Controllers
{
    public class CarerController : BaseController
    {
        private readonly IPatientService svc;

    public CarerController()
    {
        svc = new PatientServiceDb();
    }

    // GET /Carers
    public IActionResult Index()
    {
        // load carers using service and pass to view
        var carers = svc.GetAllCarers();
        
        return View(carers);
    }

    // GET /carers/details/{id}
    public IActionResult Details(int id)
    {
        var carer = svc.GetCarerById(id);
      
        // check if carers is null and alert/redirect 
        if (carer is null) {
                Alert("Carer Does not Exist", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }

        return View(carer);
    }

    // GET: /carers/create   
    public IActionResult Create()
    {
       
        //return the new carer to the view
        var carer = new User {
            Role=Role.carer
        };

        return View(carer);
    }

    // POST /carers/create
    //[ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create(User c)
    {   
      
        // complete POST action to add patient
        if (ModelState.IsValid)
        {
            // call service Addpatient method using data in s
            var carer = svc.AddCarer(c);
            if (carer is null) 
            {
                Alert("Issue creating the carer", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Details), new { Id = carer.Id});   
        }
        
        // redisplay the form for editing as there are validation errors
        return View(c);
    }

    // GET /Carer/edit/{id}
    public IActionResult Edit(int id)
    {
        // load the Carer using the service
        var carer = svc.GetCarerById(id);

        // check if Carer is null and Alert/Redirect
        if (carer is null)
        {
            Alert("Carer not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }  

        // pass patient to view for editing
        return View(carer);
    }

    // POST /patient/edit/{id}
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Edit(int id, User c)
    {       
        // complete POST action to save family member changes
        if (ModelState.IsValid)
        {            
            var carer = svc.GetCarerById(c.Id);
            if (carer is null) 
            {
                Alert("Issue editing the carer", AlertType.warning);
            }

            // redirect back to view the patient details
            return RedirectToAction(nameof(Details), new { Id = c.Id });
        }

        // redisplay the form for editing as validation errors
        return View(c);
    }

    // GET / carer/delete/{id}   
    public IActionResult Delete(int id)
    {
        // load the carer using the service
        var carer = svc.GetCarerById(id);
        // check the returned carer is not null and if so return NotFound()
        if (carer == null)
        {
            Alert("Carer not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }     
        // pass carer to view for deletion confirmation
        return View(carer);
    }

    // POST /carer/delete/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]   
    public IActionResult DeleteConfirm(int id)
    {
        // delete patient via service
        var deleted = svc.DeleteCarer(id);
        if (deleted)
        {
            Alert("Carer deleted", AlertType.success);            
        }
        else
        {
            Alert("Carer could not  be deleted", AlertType.warning);           
        }
        
        // redirect to the index view
        return RedirectToAction(nameof(Index));
    }

}
}

CMS.Web/Controllers/ConditionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CMS.Data.Services;
using CMS.Data.Entities;

namespace CMS.Web.Controllers
{
    public class ConditionController : BaseController
    {
       private readonly IPatientService svc;

    public ConditionController()
    {
        svc = new PatientServiceDb();
    }

    // GET /Conditions
    public IActionResult Index()
    {
        // load Conditions using service and pass to view
        var conditions = svc.GetAllConditions();
        
        return View(conditions);
    }

    // GET /conditions/details/{id}
    public IActionResult Details(int id)
    {
        var condition = svc.GetConditionById(id);
      
        // check if condition is null and alert/redirect 
        if (condition is null) {
            Alert("Condition Does not Exist", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }
        return View(condition);
    }

    // GET: /condition/create   
    public IActionResult Create()
    {
        var con  = new Condition();
        // display blank form to create a condition
        return View(con);
    }

    // POST /condition/create
    //[ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create(Condition con)
    {   
        // complete POST action to add condition
        if (ModelState.IsValid)
        {
            // call service Addcondition method using data in s
            var condition = svc.AddCondition(con);
            if (con is null) 
            {
                Alert("Issue creating the condition", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Details), new { Id = condition.Id});   
        }
        
        // redisplay the form for editing as there are validation errors
        return View(con);
    }

    // GET /family/edit/{id}
    public IActionResult Edit(int id)
    {
        // load the condition using the service
        var condition = svc.GetConditionById(id);

        // check if condition is null and Alert/Redirect
        if (condition is null)
        {
            Alert("Condition not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }  

        // pass patient to view for editing
        return View(condition);
    }

    // POST /patient/edit/{id}
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Edit(int id, Condition con)
    {       
        // complete POST action to save condition changes
        if (ModelState.IsValid)
        {            
            var condition = svc.UpdateCondition(con);
            if (condition is null) 
            {
                Alert("Issue editing the condition", AlertType.warning);
            }

            // redirect back to view the condition details
            return RedirectToAction(nameof(Details), new { Id = con.Id });
        }

        // redisplay the form for editing as validation errors
        return View(con);
    }

    // GET / condition/delete/{id}   
    public IActionResult Delete(int id)
    {
        // load the condition using the service
        var condition = svc.GetConditionById(id);
        // check the returned condition is not null and if so return NotFound()
        if (condition == null)
        {
            Alert("Condition not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }     
        // pass condition to view for deletion confirmation
        return View(condition);
    }
    // POST /condition/delete/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]   
    public IActionResult DeleteConfirm(int id)
    {
        // delete patient via service
        var deleted = svc.DeleteCondition(id);
        if (deleted)
        {
            Alert("Condition deleted", AlertType.success);            
        }
        else
        {
            Alert("Condition could not  be deleted", AlertType.warning);           
        }
        
        // redirect to the index view
        return RedirectToAction(nameof(Index));
    }

}
}

CMS.Web/Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
 using System;
using System.Collections.Generic;
 using System.Diagnostics;
 using System.Linq;
 using System.Threading.Tasks;
 using Microsoft.Extensions.Logging;

using CMS.Data.Services;
using CMS.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace CMS.Web.Controllers;

[Authorize]
public class PatientController : BaseController
{
    private readonly IPatientService svc;

    public PatientController()
    
    {
        svc = new PatientServiceDb();
    }

    // GET /patient/ index
    public IActionResult Index()
    {
        IList<Patient> patients;
        if (User.HasOneOfRoles("family")) 
        {
            patients = svc.GetPatientsForMember(User.GetSignedInUserId());
        }
        else{
            // load patients using service and pass to view
            patients = svc.GetAllPatients();
        }
        
        return View(patients);
    }

    // GET /patient/details/{id}
    public IActionResult Details(int id)
    { 
        // retrieve the patient with specified id from the service
        var patient = svc.GetPatientById(id);
      
        // check if patient is null and alert/redirect 
        if (patient == null) {
            Alert("Patient Does not Exist", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }
        return View(patient);
    }

    // GET: /patient/create   
    public IActionResult Create()
    {
        // display blank form to create a patient
        var p = new Patient();
        //return the new patient to the view
        return View(p);
    }

    // POST /patient/create
    //[ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create(Patient p)
    {   
        // complete POST action to add patient
        if (ModelState.IsValid)
        {
            // call service Addpatient method using data in p
            var patient = svc.AddPatient(p);
            if (patient is null) 
            {
                Alert("Issue creating the patient", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Details), new { Id = patient.Id});   
        }
        
        // redisplay the form for editing as there are validation errors
        return View(p);
    }

    // GET /patient/edit/{id}
    public IActionResult Edit(int id)
    {
        // load the patient from the service
        var patient = svc.GetPatientById(id);

        // check if patient is null and Alert/Redirect
        if (patient == null)
        {
            Alert("Patient not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }  

        // pass patient to view for editing
        return View(patient);
    }

    // POST /patient/edit/{id}
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Edit(int id, Patient p)
    {       
        // complete POST action to save patient changes
        if (ModelState.IsValid)
        {            
            var patient = svc.UpdatePatient(p);
            if (patient == null) 
            {
                Alert("Issue editing the patient", AlertType.warning);
            }

            // redirect back to view the patient details
            return RedirectToAction(nameof(Details), new { Id = p.Id });
        }

        // redisplay the form for editing as validation errors
        return View(p);
    }

    // GET / patient/delete/{id}   
    public IActionResult Delete(int id)
    {
        // load the patient using the service
        var patient = svc.GetPatientById(id);
        // check the returned patient is not null and if so return NotFound()
        if (patient == null)
        {
            Alert("Patient not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }     
        
        // pass patient to view for deletion confirmation
        return View(patient);
    }

    // POST /patient/delete/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]   
    public IActionResult DeleteConfirm(int id)
    {
        // delete patient via service
        var deleted = svc.DeletePatient(id);
        if (deleted)
        {
            Alert("patient deleted", AlertType.success);            
        }
        else
        {
            Alert("Patient could not  be deleted", AlertType.warning);           
        }
        
        // redirect to the index view
        return RedirectToAction(nameof(Index));
    }

}

CMS.Web/Views/Shared/Components/Paginator/PaginatorViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CMS.Web.Views.Shared.Components;

[ViewComponent]
public class PaginatorViewComponent : ViewComponent
{
    
    public IViewComponentResult Invoke(string action, int rows, int pages, int current, int size=10)
    {       
        // extract existing query parameters except for page and size (these will be replaced with updated values)
        var existingParams = Request.Query
            .Where(e => e.Key.ToLower() != "page" && e.Key.ToLower() != "size")
            .Select(e =>  (e.Key.ToString(),e.Value.ToString())) 
            .ToList();
        
        // build paginator pages (page no and url)
        var pageLinks = new List<Page>();
        for(var p=1; p<=pages;  p++)
        {       
            pageLinks.Add( new Page(p, BuildUrl(action, p, size, existingParams)) ); 
        }

        var props = new PaginatorProps {           
            Pages = pageLinks, 
            CurrentPage = current, 
            TotalRows = rows, 
            PageSize = size,
         };
        return View("Default", props);
    }

    // build a url for action with existing parameters plus updated page and size parameters
    private string BuildUrl(string action, int page, int size, List<(string,string)> existingParameters)
    {
        var paramsDict = new RouteValueDictionary();
        existingParameters.ForEach( p => paramsDict.Add(p.Item1,p.Item2));
        paramsDict.Add("page", page);
        paramsDict.Add("size", size); 
        return Url.Action(action, paramsDict);
    }
}

public record Page(int PageNo, string Url);

public class PaginatorProps 
{
    private int Index => CurrentPage-1; // actual Pages index

    public int CurrentPage { get; set; } // 1..Pages.Count
    public List<Page> Pages { get; set; }
    public int TotalRows { get; set; }
    public int PageSize { get; set; }

    // read-only props
    public int TotalPages => Pages.Count;
    public Page NextPage => HasNextPage ? Pages[Index+1] : null;
    public Page PreviousPage => HasPreviousPage ? Pages[Index-1] : null;
    public Page FirstPage => Pages.FirstOrDefault();
    public Page LastPage => Pages.LastOrDefault();
 
    public bool HasPreviousPage => CurrentPage > 1;
    public bool HasNextPage => CurrentPage < TotalPages;
    public bool AtLastPage => !HasNextPage;
    public bool AtFirstPage => !HasPreviousPage;
}

CMS.Web/Views/Shared/Components/SortOrder/SortOrderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CMS.Web.Views.Shared.Components;

[ViewComponent]
public class SortOrderViewComponent : ViewComponent
{

    public IViewComponentResult Invoke(string field="Id", string orderby="Id", string direction = "asc")
    {      
        return View("Default", new SortOrderProps(field.ToLower(), orderby.ToLower(), direction.ToLower()) );
    }
}

public record SortOrderProps(string Field ="Id", string OrderBy="Id", string Direction="asc");

CMS.Web/Views/Shared/_Alert.cshtml
<!-- AMC - alert partial to display any alerts via layout cms -->
@{
    var message = TempData["Alert.Message"] ?? null;
    var type    = TempData["Alert.Type"]    ?? null;
}
@if (message != null)
{
    <div class="alert alert-@type alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

CMS.Web/Views/Shared/_BreadCrumbs.cshtml
<!-- model contains array of breadcrumb tuples (link,crumb) -->
@model IList<(string,string)>

@if (Model != null ) {
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      @foreach(var (link,crumb) in Model)
      {
          @if (link == null || link.Length == 0)
          {
              <li class="breadcrumb-item active" aria-current="page">@crumb</li>
          }
          else
          {
              <li class="breadcrumb-item"><a href="@link">@crumb</a></li>
          }
      }
    </ol>
  </nav>
}

CMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CMS.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-lg rounded mb-3">
        @* <nav class="navbar navbar-expand-md navbar-light bg-white shadow-lg rounded mb-3"> *@
            <div class="container">
                <a class="navbar-brand" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-exclude" viewBox="0 0 16 16">
                        <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm12 2H5a1 1 0 0 0-1 1v7h7a1 1 0 0 0 1-1V4z"/>
                    </svg>
                    <span>CMS</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <a class="nav-link" asp-controller="User" asp-action="Index"
                            asp-roles="admin, manager">Users</a>
                        <a class="nav-link" asp-controller="Condition" asp-action="Index"
                            asp-roles="manager, admin">Conditions</a>
                        <a class="nav-link " asp-controller="Patient" asp-action="Index"
                            asp-roles="manager, admin">Patients</a>
                        <a class="nav-link " asp-controller="Carer" asp-action="Index"
                            asp-roles="manager, admin">Carers</a>
                        @* <a class="nav-link" asp-controller="Appointment" asp-action="Index"
                            asp-roles="manager, admin">All Appointments</a> *@
                        @* <a class="nav-link" asp-controller="Appointment" asp-action="MyAppointments"
                            asp-roles="manager, admin, carer">My Appointments</a> *@
                        <a class="nav-link" asp-controller="PatientCareEvent" asp-action="Index"
                            asp-roles="manager, admin">All Appointments</a>
                        <a class="nav-link" asp-controller="PatientCareEvent" asp-action="Scheduled"
                            asp-roles="manager, admin, carer">My Appointments</a>
                    </div>
                    <!-- AMC The login partial is added here for authentication -->
                    <partial name="_LoginPartial" />      
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        
        <!-- AMC Any alert defined in controller is rendered here -->
        <partial name="_Alert" />

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - CMS.Web - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>